name: CI
env:
  app_name    : "Test"
  package_name: "Test file-${{github.sha}}"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  my-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World from testing
      run : echo "Hello World"
      
    - name: Print few comands
      run : |
        echo "Hello message 1"
        echo "Hello message 2"
        echo "Application name is: ${{ env.app_name }}"
      
    - name: Git clone my repo
      uses: actions/checkout@1
      
    - name: List current folders
      run : ls -la

  my-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World from deploy
      run : echo "Hello World"
      
    - name: Print few comands
      run : |
        echo "Hello message 1"
        echo "Hello message 2"
        echo "Deploy name is: ${{ env.package_name }}"
