name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  my-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World from testing
      run : echo "Hello World"
      
    - name: Print few comands
      run : |
        echo "Hello message 1"
        echo "Hello message 2"
        echo "Application name is: ${{ env.app_name }}"
      
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: List current folders
      run : ls -la
